# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebRTCDemo-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebRTCDemo-iOS
  pod 'GoogleWebRTC','~>1.1.31999'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Starscream', '~> 4.0.0'
end
